name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza a cada 24h

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: kaylancds
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando a cobrinha 🐍"
          branch: output
